name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Create Firebase config from secrets
      run: |
        cat > firebase-config-secret.js << EOF
        export default {
          apiKey: "${{ secrets.FIREBASE_API_KEY }}",
          authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
          projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
          storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
          messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
          appId: "${{ secrets.FIREBASE_APP_ID }}"
        };
        EOF
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        exclude_assets: |
          .github/
          node_modules/
          .git/
          .gitignore
          firebase-config-secret.js.template
          FIREBASE_SETUP.md